import { http } from "@/lib/http";
import type {
  AdvancedQueryParams,
  ApiResponse,
  ApiResponseOffset,
} from "@/lib/types";

/**
 * Report interfaces based on backend DTOs
 */
export interface Report {
  id: string;
  userId: string;
  reportableType: string;
  reportableId: string;
  reason: string;
  description?: string;
  status: string;
  priority?: string;
  moderatorId?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  resolution?: string;
  isAutoGenerated?: boolean;
  metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  user?: {
    id: string;
    name?: string;
    username?: string;
  };
  moderator?: {
    id: string;
    name?: string;
    username?: string;
  };
  actions?: ReportAction[];
}

export interface ReportAction {
  id: string;
  reportId: string;
  userId: string;
  action: string;
  description?: string;
  createdAt: string;
}

export interface CreateReportDto {
  reportableType: string;
  reportableId: string;
  reason: string;
  description?: string;
  priority?: string;
  isAutoGenerated?: boolean;
  metadata?: Record<string, unknown>;
}

export interface UpdateReportDto {
  reason?: string;
  description?: string;
  status?: string;
  priority?: string;
}

export interface CreateReportActionDto {
  reportId: string;
  action: string;
  description?: string;
}

export interface QueryReportsDto extends AdvancedQueryParams {
  status?: string;
  priority?: string;
  reportableType?: string;
  reason?: string;
  userId?: string;
  moderatorId?: string;
  reportableId?: string;
  isAutoGenerated?: boolean;
  createdAfter?: string;
  createdBefore?: string;
  assignedAfter?: string;
  assignedBefore?: string;
  resolvedAfter?: string;
  resolvedBefore?: string;
  minDuplicateCount?: number;
  maxDuplicateCount?: number;
}

export interface ResolveReportDto {
  resolution: string;
  action?: string;
}

export interface AssignReportDto {
  moderatorId: string;
}

export interface DismissReportDto {
  reason: string;
}

export interface EscalateReportDto {
  reason: string;
}

export interface MergeReportsDto {
  reportIds: string[];
}

export interface ReportStatsDto {
  total: number;
  pending: number;
  resolved: number;
  dismissed: number;
  byType: Array<{
    type: string;
    count: number;
  }>;
  byPriority: Array<{
    priority: string;
    count: number;
  }>;
  byStatus: Array<{
    status: string;
    count: number;
  }>;
}

/**
 * Reports API wrapper
 * Handles all report-related API calls
 */
export class ReportsAPI {
  private static readonly BASE_URL = "/reports";

  /**
   * Create a new report
   */
  static async createReport(
    data: CreateReportDto,
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(this.BASE_URL, data);
    return response.data;
  }

  /**
   * Get reports with pagination and filtering
   */
  static async getReports(
    params?: QueryReportsDto,
  ): Promise<ApiResponseOffset<Report>> {
    const response = await http.get<ApiResponseOffset<Report>>(this.BASE_URL, {
      params,
    });
    return response.data;
  }

  /**
   * Get a single report by ID
   */
  static async getReport(reportId: string): Promise<ApiResponse<Report>> {
    const response = await http.get<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}`,
    );
    return response.data;
  }

  /**
   * Update a report
   */
  static async updateReport(
    reportId: string,
    data: UpdateReportDto,
  ): Promise<ApiResponse<Report>> {
    const response = await http.put<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}`,
      data,
    );
    return response.data;
  }

  /**
   * Assign a report to a moderator
   */
  static async assignReport(
    reportId: string,
    moderatorId: string,
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}/assign`,
      { moderatorId },
    );
    return response.data;
  }

  /**
   * Resolve a report
   */
  static async resolveReport(
    reportId: string,
    data: ResolveReportDto,
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}/resolve`,
      data,
    );
    return response.data;
  }

  /**
   * Dismiss a report
   */
  static async dismissReport(
    reportId: string,
    reason: string,
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}/dismiss`,
      { reason },
    );
    return response.data;
  }

  /**
   * Escalate a report
   */
  static async escalateReport(
    reportId: string,
    reason: string,
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(
      `${this.BASE_URL}/${reportId}/escalate`,
      { reason },
    );
    return response.data;
  }

  /**
   * Create a report action
   */
  static async createReportAction(
    reportId: string,
    data: Omit<CreateReportActionDto, "reportId">,
  ): Promise<ApiResponse<ReportAction>> {
    const response = await http.post<ApiResponse<ReportAction>>(
      `${this.BASE_URL}/${reportId}/actions`,
      data,
    );
    return response.data;
  }

  /**
   * Get reports for specific content
   */
  static async getReportsForContent(
    reportableType: string,
    reportableId: string,
  ): Promise<ApiResponse<Report[]>> {
    const response = await http.get<ApiResponse<Report[]>>(
      `${this.BASE_URL}/content/${reportableType}/${reportableId}`,
    );
    return response.data;
  }

  /**
   * Get duplicate reports
   */
  static async getDuplicateReports(
    reportableType: string,
    reportableId: string,
  ): Promise<ApiResponse<Report[]>> {
    const response = await http.get<ApiResponse<Report[]>>(
      `${this.BASE_URL}/duplicates/${reportableType}/${reportableId}`,
    );
    return response.data;
  }

  /**
   * Merge duplicate reports
   */
  static async mergeDuplicateReports(
    reportIds: string[],
  ): Promise<ApiResponse<Report>> {
    const response = await http.post<ApiResponse<Report>>(
      `${this.BASE_URL}/merge`,
      { reportIds },
    );
    return response.data;
  }

  /**
   * Get report statistics
   */
  static async getReportStats(
    params?: QueryReportsDto,
  ): Promise<ApiResponse<ReportStatsDto>> {
    const response = await http.get<ApiResponse<ReportStatsDto>>(
      `${this.BASE_URL}/stats`,
      { params },
    );
    return response.data;
  }

  /**
   * Get my reports (for regular users)
   */
  static async getMyReports(
    params?: Omit<QueryReportsDto, "userId">,
  ): Promise<ApiResponseOffset<Report>> {
    const response = await http.get<ApiResponseOffset<Report>>(
      `${this.BASE_URL}/my`,
      { params },
    );
    return response.data;
  }

  /**
   * Get reports assigned to me (for moderators)
   */
  static async getAssignedReports(
    params?: Omit<QueryReportsDto, "moderatorId">,
  ): Promise<ApiResponseOffset<Report>> {
    const response = await http.get<ApiResponseOffset<Report>>(
      `${this.BASE_URL}/assigned`,
      { params },
    );
    return response.data;
  }

  /**
   * Get pending reports (for moderators)
   */
  static async getPendingReports(
    params?: Omit<QueryReportsDto, "status">,
  ): Promise<ApiResponseOffset<Report>> {
    const response = await http.get<ApiResponseOffset<Report>>(
      `${this.BASE_URL}/pending`,
      { params },
    );
    return response.data;
  }

  /**
   * Get urgent reports (for moderators)
   */
  static async getUrgentReports(
    params?: Omit<QueryReportsDto, "priority">,
  ): Promise<ApiResponseOffset<Report>> {
    const response = await http.get<ApiResponseOffset<Report>>(
      `${this.BASE_URL}/urgent`,
      { params },
    );
    return response.data;
  }
}
