import { SiteFooter, SiteNav } from "@/components/features/navigation";
import {
  AuthProvider,
  GoogleOneTapProvider,
  I18nProvider,
  LoadingProvider,
  NoSSR,
  RateLimitProvider,
  ReactQueryProvider,
  ThemeProvider,
} from "@/components/providers";
import { Toaster } from "@/components/ui";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        {/* Suppress FedCM experimental errors in console */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                if (typeof window === 'undefined') return;
                const originalError = console.error;
                const originalWarn = console.warn;
                console.error = function(...args) {
                  const msg = args[0]?.toString() || '';
                  if (msg.includes('FedCM') || msg.includes('GSI_LOGGER') || msg.includes('AbortError: signal is aborted')) {
                    return;
                  }
                  originalError.apply(console, args);
                };
                console.warn = function(...args) {
                  const msg = args[0]?.toString() || '';
                  if (msg.includes('FedCM') || msg.includes('GSI_LOGGER')) {
                    return;
                  }
                  originalWarn.apply(console, args);
                };
              })();
            `,
          }}
        />
        {/* Google Identity Services - Required for Google One Tap */}
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
        suppressHydrationWarning={true}
      >
        <NoSSR>
          <ReactQueryProvider>
            <I18nProvider>
              <ThemeProvider>
                <AuthProvider>
                  <LoadingProvider>
                    <RateLimitProvider>
                      {/* Global Google One Tap - Shows on all pages when not authenticated */}
                      <GoogleOneTapProvider />
                      <SiteNav />
                      {children}
                      <SiteFooter />
                    </RateLimitProvider>
                  </LoadingProvider>
                </AuthProvider>
              </ThemeProvider>
            </I18nProvider>
          </ReactQueryProvider>
        </NoSSR>
        <Toaster richColors position="top-center" expand={true} />
      </body>
    </html>
  );
}
