import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui";
import AuthProvider from "@/components/providers/auth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NoSSR } from "@/components/providers/no-ssr";
import { LoadingProvider } from "@/components/providers/loading-provider";
import { I18nProvider } from "@/components/providers/i18n-provider";
import { SiteNav } from "@/components/features/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
        suppressHydrationWarning={true}
      >
        <NoSSR>
          <I18nProvider>
            <ThemeProvider>
              <AuthProvider>
                <LoadingProvider>
                  <SiteNav />
                  {children}
                </LoadingProvider>
              </AuthProvider>
            </ThemeProvider>
          </I18nProvider>
        </NoSSR>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
